### ISSUE TITLE
USER STORY: View List of Posts

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/gabby-gourmand#1]
As a **site user** I can **view a list of posts** so that **I can choose a post I want to view**

### Acceptance Criteria:

- Acceptance Criteria 1: If there is more than one post available, multiple posts should be listed.
- Acceptance Criteria 2: A list of available posts should be visible when the user clicks on the main page.
- Acceptance Criteria 2: The user sees a list of all available posts, with pagination.

### Tasks:

- [ ] Create main page.
- [ ] Add mutiple posts to be viewed.
- [ ] Add / ensure pagination if number of posts do not fit on one page.
