### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by Jem212Mac** [Jem212Mac/gabby-gourmand#4]
As a **site user** I can **register for an account** so that **I can comment on posts**

### Acceptance Criteria:

- Acceptance Criteria 1: A user can register an account with an email address.
- Acceptance Criteria 2: Once registered, a user can log in.
- Acceptance Criteria 2: When logged in, a user can comment on a post.

### Tasks:

- [ ] Create an account registration page.
- [ ] Create a log in page.
- [ ] Create ability for logged in user to comment on an existing post.
